version: '3.4'

services:
  anonq:
    image: ${DOCKER_REGISTRY-}anonq
    build:
      context: .
      dockerfile: AnonQ/Dockerfile

  anonqjobs:
    image: ${DOCKER_REGISTRY-}anonqjobs
    build:
      context: .
      dockerfile: AnonQJobs/Dockerfile

  anonq-react:
    image: anonq-react
    container_name: anonq-react
    build:
      context: .
      dockerfile: anonq-react/Dockerfile
    stdin_open: true
    ports:
      - 3010:3000
    volumes:
      - './anonq-react:/app'
    environment:
      - CHOKIDAR_USEPOLLING=true

  anonq-adminpanel:
    image: anonq-adminpanel
    container_name: anonq-adminpanel
    build:
      context: .
      dockerfile: anonq-adminpanel/Dockerfile
    stdin_open: true
    ports:
      - 3020:3000
    volumes:
      - './anonq-adminpanel:/app'
    environment:
      - CHOKIDAR_USEPOLLING=true
